In [1]:
import numpy as np

In [2]:
A=np.array([1,2])
B=np.array([3,4,5])
A

array([1, 2])

In [3]:
B

array([3, 4, 5])

In [5]:
A=[1,2]
B=[2,4]
va=np.array(A)
vb=np.array(B)
print(va+vb)
print(A+B)

[3 6]
[1, 2, 2, 4]


In [6]:
print(va-vb)
print(vb-va)

[-1 -2]
[1 2]


In [7]:
i=3
f=0.5
print(i*va)
print(f*va)

[3 6]
[0.5 1. ]


In [8]:
vc=np.array([3,4,5])
vc[1]=6
print(vc)

[3 6 5]


In [10]:
vz=np.zeros(3)
vz

array([0., 0., 0.])

In [11]:
ex=np.array([1,0,0])
ey=np.array([0,1,0])
ez=np.array([0,0,1])


In [14]:
nva=np.linalg.norm(va)
nva

np.float64(2.23606797749979)

In [15]:
n=0
for e in va:
    n+=e*e
n**=0.5
print(n)

2.23606797749979


In [ ]:
va_normalized=va/nva
va_normalized

array([0.4472136 , 0.89442719])

In [17]:
np.linalg.norm(va_normalized)

np.float64(0.9999999999999999)

In [18]:
C=[2,5]
D=[1,-8]
vc=np.array(C)
vd=np.array(D)
np.dot(vc,vd)

np.int64(-38)

In [19]:
vc@vd

np.int64(-38)