In [62]:
import numpy as np

In [63]:
a=np.array([2,3])
b=np.array([4,-1])
a,b

(array([2, 3]), array([ 4, -1]))

In [64]:
a+b

array([6, 2])

In [65]:
a-b

array([-2,  4])

In [66]:
3*a

array([6, 9])

In [67]:
c=np.array([1,2,3])
d=np.array([-1,0,2])
c,d

(array([1, 2, 3]), array([-1,  0,  2]))

In [68]:
c+d

array([0, 2, 5])

In [69]:
#7
norm_a=np.linalg.norm(a)
norm_a

np.float64(3.605551275463989)

In [70]:
#8
norm_c=np.linalg.norm(c)
norm_c

np.float64(3.7416573867739413)

In [71]:
a@b

np.int64(5)

In [72]:
#10
c@d

np.int64(5)

In [73]:
#11
e=np.array([1,3**0.5])
f=np.array([3**0.5,1])
cos_theta=e@f/(np.linalg.norm(e)*np.linalg.norm(f))
print(cos_theta)
theta=np.arccos(cos_theta)
print(theta)
print(np.degrees(theta))
#12
g=np.array([1,0,0])
h=np.array([0,1,1])
cos_theta=g@h/(np.linalg.norm(g)*np.linalg.norm(h))
print(cos_theta)
theta=np.arccos(cos_theta)
print(theta)
#12
print(np.degrees(theta))


0.8660254037844388
0.5235987755982985
29.99999999999998
0.0
1.5707963267948966
90.0


In [74]:
i=np.array([3,4])
norm_i=np.linalg.norm(i)
p_i=i/norm_i
print(p_i)
p_i@p_i

[0.6 0.8]


np.float64(1.0)

In [75]:
#14
j=np.array([1,-2,2])
norm_j=np.linalg.norm(j)
p_j=j/norm_j
print(p_j)
p_j@p_j

[ 0.33333333 -0.66666667  0.66666667]


np.float64(1.0)

In [76]:
#15
def are_orthogonal_2d(v1,v2):
    if v1@v2==0:
        return True
    return False

u=np.array([999,0])
v=np.array([0,9999])
are_orthogonal_2d(u,v)

True

In [77]:
#16
u=np.array([1,1,0])
v=np.array([1,-1,1])
w=np.array([-1,1,2])
print(u@v)
print(u@w)
print(v@w)

0
0
0


In [78]:
#17
p=np.array([2,1])
q=np.array([3,4])
pq=np.array([p,q])
np.linalg.det(pq)

np.float64(5.000000000000001)

In [79]:
#18
r=np.array([1,2,3])
s=np.array([4,5,6])
rs=np.cross(r,s)
print(rs)

[-3  6 -3]


In [80]:
print(r@rs)
print(s@rs)

0
0


In [81]:
#20
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])